### ISSUE TITLE
 Database Exception (#42000)

### ISSUE THREAD

**Issue by umair-iftikhar** [EduSec/EduSec#11]
What is this error in your github free version? Login as Admin and try to open Report Center.

> **Database Exception (#42000)**
> 
> An internal server error occurred.
> 
> The above error occurred while the Web server was processing your request.
> 
> Please contact us if you think this is a server error. Thank you.
>

**Comment by rudrasoftech** [comment]
This version of EduSec is supported by PHP5.4, MySQL 5.4 
Hope this will help you.

**Comment by umair-iftikhar** [comment]
I have the same versions.... complete software is working fine.  Error is in only "Report Center"
